/*
	Icons
*/

-----------------------------------------------
-- IconTextureAtlases
-----------------------------------------------
INSERT INTO	IconTextureAtlases
		(Name,								IconSize,	IconsPerRow,	IconsPerColumn,	Filename							)
VALUES	('ICON_ATLAS_TROS_CITYSTATES',		256,		5,				5,				'TROS_CITYSTATES_ICONS_256.dds'		),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	256,		4,				4,				'TROS_CIVILIZATIONS_ICONS_256.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	80,			4,				4,				'TROS_CIVILIZATIONS_ICONS_80.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	64,			4,				4,				'TROS_CIVILIZATIONS_ICONS_64.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	50,			4,				4,				'TROS_CIVILIZATIONS_ICONS_50.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	48,			4,				4,				'TROS_CIVILIZATIONS_ICONS_48.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	44,			4,				4,				'TROS_CIVILIZATIONS_ICONS_44.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	36,			4,				4,				'TROS_CIVILIZATIONS_ICONS_36.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	30,			4,				4,				'TROS_CIVILIZATIONS_ICONS_30.dds'	),
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	22,			4,				4,				'TROS_CIVILIZATIONS_ICONS_22.dds'	);
		--('ICON_ATLAS_TROS_CIVILIZATIONS',	45,			4,				4,				'TROS_CIVILIZATIONS_ICONS_45.dds'	);



-----------------------------------------------
-- IconDefinitions
-----------------------------------------------
INSERT INTO	IconDefinitions
		(Name,											Atlas,								'Index'	)
VALUES	('ICON_CITYSTATE_TROS_CS1',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS2',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS3',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS4',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS5',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		--('ICON_CITYSTATE_TROS_CS6',						'ICON_ATLAS_TROS_CITYSTATES',		0		), -- Genf
		('ICON_CITYSTATE_TROS_CS7',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS8',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS9',						'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS10',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS11',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS12',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS13',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS14',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS15',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS16',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS17',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS18',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS19',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS20',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS21',					'ICON_ATLAS_TROS_CITYSTATES',		0		),
		('ICON_CITYSTATE_TROS_CS22',					'ICON_ATLAS_TROS_CITYSTATES',		0		);

		--('ICON_CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'ICON_ATLAS_TROS_CIVILIZATIONS',	1		),
		--('ICON_CIVILIZATION_TROS_FRANKREICH',			'ICON_ATLAS_TROS_CIVILIZATIONS',	2		),
		--('ICON_CIVILIZATION_TROS_BURGUND',				'ICON_ATLAS_TROS_CIVILIZATIONS',	3		),
		--('ICON_CIVILIZATION_TROS_SAVOYEN',				'ICON_ATLAS_TROS_CIVILIZATIONS',	4		),
		--('ICON_CIVILIZATION_TROS_DEUTSCHLAND',			'ICON_ATLAS_TROS_CIVILIZATIONS',	5		),
		--('ICON_CIVILIZATION_TROS_MAILAND',				'ICON_ATLAS_TROS_CIVILIZATIONS',	6		),
		--('ICON_CIVILIZATION_TROS_HABSBURG',				'ICON_ATLAS_TROS_CIVILIZATIONS',	7		),
		--('ICON_CIVILIZATION_TROS_ZURICH',				'ICON_ATLAS_TROS_CIVILIZATIONS',	8		),
		--('ICON_CIVILIZATION_TROS_BERN',					'ICON_ATLAS_TROS_CIVILIZATIONS',	9		),
		--('ICON_CIVILIZATION_TROS_GRAUBUNDEN',			'ICON_ATLAS_TROS_CIVILIZATIONS',	10		),
		--('ICON_CIVILIZATION_TROS_WALLIS',				'ICON_ATLAS_TROS_CIVILIZATIONS',	11		);