/*
	Localisation
*/

/*
	Notes:

	File > Advanced Save Options... > Encoding: Unicode (UTF-8 without signature) - Codepage 65001
	
*/


-----------------------------------------------
-- LocalizedText
-----------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, Language, Text)
VALUES

-----------------------------------------------
-- Cities
-----------------------------------------------

-- CIV1  - Eidgenossenschaft ------------------
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_1",	"en_US",	"Schwyz"), -- wenn de_DE nicht definiert, sollte automatisch en_US übernehmen
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_2",	"en_US",	"Altdorf"),
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_3",	"en_US",	"Sarnen"),
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_4",	"en_US",	"Andermatt"),
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_5",	"en_US",	"Bellinzona"),
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_6",	"en_US",	"Zofingen"),
	-- Achtung: Placeholder
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_7",	"en_US",	"Placeholder"),
	("LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_7",	"de_DE",	"Pläcehölder"),
-- CIV2  - Frankreich -------------------------
-- CIV3  - Burgund ----------------------------
	("LOC_CITY_NAME_TROS_BURGUND_1", "en_US", "Dijon"),
	("LOC_CITY_NAME_TROS_BURGUND_2", "en_US", "Dole"),
	("LOC_CITY_NAME_TROS_BURGUND_3", "en_US", "Montbeliard"),
	("LOC_CITY_NAME_TROS_BURGUND_3", "de_DE", "Montbéliard"),
	("LOC_CITY_NAME_TROS_BURGUND_4", "en_US", "Oyonnax"),
	("LOC_CITY_NAME_TROS_BURGUND_5", "en_US", "Pontarlier"),
	("LOC_CITY_NAME_TROS_BURGUND_6", "en_US", "Plaecholder"),
-- CIV4  - Savoyen ----------------------------
	("LOC_CITY_NAME_TROS_SAVOYEN_1", "en_US", "Chambéry"),
	("LOC_CITY_NAME_TROS_SAVOYEN_2", "en_US", "Annecy"),
	("LOC_CITY_NAME_TROS_SAVOYEN_3", "en_US", "Vevey"),
	("LOC_CITY_NAME_TROS_SAVOYEN_4", "en_US", "Yverdon"),
	("LOC_CITY_NAME_TROS_SAVOYEN_5", "en_US", "Evian"),
	("LOC_CITY_NAME_TROS_SAVOYEN_6", "en_US", "Bourg-en-Bresse"),
	("LOC_CITY_NAME_TROS_SAVOYEN_7", "en_US", "Monthey"),
	("LOC_CITY_NAME_TROS_SAVOYEN_8", "en_US", "Martigny"),
	("LOC_CITY_NAME_TROS_SAVOYEN_9", "en_US", "Aosta"),
	("LOC_CITY_NAME_TROS_SAVOYEN_10", "en_US", "Nyon"),
	("LOC_CITY_NAME_TROS_SAVOYEN_11", "en_US", "Plaecholder"),
-- CIV5  - Deutschland ------------------------
-- CIV6  - Italien ----------------------------
-- CIV7  - Habsburg ---------------------------
	("LOC_CITY_NAME_TROS_HABSBURG_1", "en_US", "Brugg"),
	("LOC_CITY_NAME_TROS_HABSBURG_2", "en_US", "Aarau"),
	("LOC_CITY_NAME_TROS_HABSBURG_3", "en_US", "Innsbruck"),
	("LOC_CITY_NAME_TROS_HABSBURG_4", "en_US", "Winterthur"),
	("LOC_CITY_NAME_TROS_HABSBURG_5", "en_US", "Zug"),
	("LOC_CITY_NAME_TROS_HABSBURG_6", "en_US", "Frauenfeld"),
	("LOC_CITY_NAME_TROS_HABSBURG_7", "en_US", "Belfort"),
	("LOC_CITY_NAME_TROS_HABSBURG_8", "en_US", "Waldshut"),
	("LOC_CITY_NAME_TROS_HABSBURG_9", "en_US", "Garmisch-Partenkirchen"),
	("LOC_CITY_NAME_TROS_HABSBURG_10", "en_US", "Dornbirn"),
	("LOC_CITY_NAME_TROS_HABSBURG_11", "en_US", "Feldkirch"),
	("LOC_CITY_NAME_TROS_HABSBURG_12", "en_US", "Plaecholder"),
-- CIV8  - Zürich -----------------------------
	("LOC_CITY_NAME_TROS_ZURICH_1", "en_US", "Zurich"),
	("LOC_CITY_NAME_TROS_ZURICH_1", "de_DE", "Zürich"),
	("LOC_CITY_NAME_TROS_ZURICH_2", "en_US", "Rapperswil"),
	("LOC_CITY_NAME_TROS_ZURICH_3", "en_US", "Plaecholder"),
-- CIV9  - Bern -------------------------------
	("LOC_CITY_NAME_TROS_BERN_1", "en_US", "Bern"),
	("LOC_CITY_NAME_TROS_BERN_2", "en_US", "Interlaken"),
	("LOC_CITY_NAME_TROS_BERN_3", "en_US", "Simmental"),
	("LOC_CITY_NAME_TROS_BERN_4", "en_US", "Thun"),
	("LOC_CITY_NAME_TROS_BERN_5", "en_US", "Murten"),
	("LOC_CITY_NAME_TROS_BERN_6", "en_US", "Porrentruy"),
	("LOC_CITY_NAME_TROS_BERN_7", "en_US", "Burgdorf"),
-- CIV10 - Graubünden -------------------------
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_1",		"en_US", "Chur"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_2", "en_US", "Disentis"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_3", "en_US", "Klosters"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_4", "en_US", "Samedan"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_5", "en_US", "Chiavenna"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_6", "en_US", "Zofingen"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_7", "en_US", "Mals"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_8", "en_US", "Sondrio"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_9", "en_US", "PlaecholderGR9"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_10",	"en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_11", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_12", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_13", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_14", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_15", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_16", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_17", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_18", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_19", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_20", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_21", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_22", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_23", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_24", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_25", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_26", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_27", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_28", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_29", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_30", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_31", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_32", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_33", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_34", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_35", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_36", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_37", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_38", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_GRAUBUNDEN_39", "en_US", "Plaecholder"),
-- CIV11 - Wallis -----------------------------
	("LOC_CITY_NAME_TROS_WALLIS_1", "en_US", "Sion"),
	("LOC_CITY_NAME_TROS_WALLIS_2", "en_US", "Brig"),
	("LOC_CITY_NAME_TROS_WALLIS_3", "en_US", "Zermatt"),
	("LOC_CITY_NAME_TROS_WALLIS_4", "en_US", "Siders"),
	("LOC_CITY_NAME_TROS_WALLIS_5", "en_US", "PlaecholderVS5"),
	("LOC_CITY_NAME_TROS_WALLIS_6", "en_US", "PlaecholderVS6"),
	("LOC_CITY_NAME_TROS_WALLIS_7", "en_US", "PlaecholderVS7"),
	("LOC_CITY_NAME_TROS_WALLIS_8", "en_US", "PlaecholderVS8"),
	("LOC_CITY_NAME_TROS_WALLIS_9", "en_US", "PlaecholderVS9"),
	("LOC_CITY_NAME_TROS_WALLIS_10", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_11", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_12", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_13", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_14", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_15", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_16", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_17", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_18", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_19", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_20", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_21", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_22", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_23", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_24", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_25", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_26", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_27", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_28", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_29", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_30", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_31", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_32", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_33", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_34", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_35", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_36", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_37", "en_US", "Plaecholder"),
	("LOC_CITY_NAME_TROS_WALLIS_38", "en_US", "Plaecholder"),

-----------------------------------------------
-- Citizens
-----------------------------------------------

-- CIV1  - Eidgenossenschaft ------------------
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_1",		"en_US",	"Willhelm"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_2",		"en_US",	"Werner"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_3",		"en_US",	"Hans"),
		-- Achtung: Placeholder
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_4",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_5",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_6",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_7",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_8",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_9",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_10",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_1",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_2",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_3",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_4",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_5",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_6",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_7",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_8",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_9",		"en_US",	"Placeholder"),
	("LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_10",	"en_US",	"Placeholder"),
-- CIV2  - Frankreich -------------------------
-- CIV3  - Burgund ----------------------------
	("LOC_CITIZEN_TROS_BURGUND_MALE_1",		"en_US",	"Charles"		),
	("LOC_CITIZEN_TROS_BURGUND_MALE_2",		"en_US",	"Placeholder"		),
	("LOC_CITIZEN_TROS_BURGUND_MALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_1",		"en_US",	"Catherine"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_2",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BURGUND_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV4  - Savoyen ----------------------------
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_1",		"en_US",	"Viktor"		),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_2",		"en_US",	"Placeholder"		),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_1",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_2",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_SAVOYEN_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV5  - Deutschland ------------------------
-- CIV6  - Italien ----------------------------
-- CIV7  - Habsburg ---------------------------
	("LOC_CITIZEN_TROS_HABSBURG_MALE_1",		"en_US",	"Ruedi"		),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_2",		"en_US",	"Placeholder"		),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_1",		"en_US",	"Sissi"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_2",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_HABSBURG_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV8  - Zürich -----------------------------
	("LOC_CITIZEN_TROS_ZURICH_MALE_1",		"en_US",	"Fredi"		),
	("LOC_CITIZEN_TROS_ZURICH_MALE_2",		"en_US",	"Hans"		),
	("LOC_CITIZEN_TROS_ZURICH_MALE_3",		"en_US",	"Felix"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_4",		"en_US",	"Urs"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_5",		"en_US",	"Exuperantius"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_1",		"en_US",	"Anna"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_2",		"en_US",	"Regula"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_3",		"en_US",	"Lydia"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_ZURICH_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV9  - Bern -------------------------------
	("LOC_CITIZEN_TROS_BERN_MALE_1",		"en_US",	"Köbi"		),
	("LOC_CITIZEN_TROS_BERN_MALE_1",		"de_DE",	"Köbi"		),
	("LOC_CITIZEN_TROS_BERN_MALE_2",		"en_US",	"Hans"		),
	("LOC_CITIZEN_TROS_BERN_MALE_3",		"en_US",	"Niklaus"	),
	("LOC_CITIZEN_TROS_BERN_MALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_1",		"en_US",	"Barbara"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_2",		"en_US",	"Magdalena"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_3",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_BERN_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV10 - Graubünden -------------------------
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_1",		"en_US",	"Andreas"		),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_2",		"en_US",	"Ursin"		),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_3",		"en_US",	"Caspar"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_4",		"en_US",	"Reto"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_1",		"en_US",	"Ursina"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_2",		"en_US",	"Katharina"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_3",		"en_US",	"Susanna"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_4",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_GRAUBUNDEN_FEMALE_10",	"en_US",	"Placeholder"	),
-- CIV11 - Wallis -----------------------------
	("LOC_CITIZEN_TROS_WALLIS_MALE_1",		"en_US",	"Boniface"		),
	("LOC_CITIZEN_TROS_WALLIS_MALE_2",		"en_US",	"Aymon"		),
	("LOC_CITIZEN_TROS_WALLIS_MALE_3",		"en_US",	"Philippe"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_4",		"en_US",	"Christian"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_5",		"en_US",	"Gianni"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_6",		"en_US",	"Joseph"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_7",		"en_US",	"Sepp"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_8",		"en_US",	"Reto"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_MALE_10",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_1",		"en_US",	"Maria"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_2",		"en_US",	"Anna"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_3",		"en_US",	"Ursula"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_4",		"en_US",	"Elisabeth"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_5",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_6",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_7",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_8",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_9",		"en_US",	"Placeholder"	),
	("LOC_CITIZEN_TROS_WALLIS_FEMALE_10",	"en_US",	"Placeholder"	),

-----------------------------------------------
-- Info
-----------------------------------------------

-- CIV1  - Eidgenossenschaft ------------------
	("LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_LOCATION",		"de_DE",	"Europa"),
	("LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_SIZE",			"de_DE",	"Etwa 41.300 Quadratkilometer"),
	("LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_POPULATION",	"de_DE",	"Etwa 8,57 Millionen"),
	("LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_CAPITAL",		"de_DE",	"Bern"),
-- CIV2  - Frankreich -------------------------
-- CIV3  - Burgund ----------------------------
	("LOC_CIVINFO_TROS_BURGUND_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_BURGUND_SIZE",			"en_US",	"?"	),
	("LOC_CIVINFO_TROS_BURGUND_POPULATION",		"en_US",	"?"	),
	("LOC_CIVINFO_TROS_BURGUND_CAPITAL",			"en_US",	"?"	),
-- CIV4  - Savoyen ----------------------------
	("LOC_CIVINFO_TROS_SAVOYEN_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_SAVOYEN_SIZE",			"en_US",	"?"	),
	("LOC_CIVINFO_TROS_SAVOYEN_POPULATION",		"en_US",	"?"	),
	("LOC_CIVINFO_TROS_SAVOYEN_CAPITAL",			"en_US",	"?"	),
-- CIV5  - Deutschland ------------------------
-- CIV6  - Italien ----------------------------
-- CIV7  - Habsburg ---------------------------
	("LOC_CIVINFO_TROS_HABSBURG_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_HABSBURG_SIZE",			"en_US",	"Unknown"	),
	("LOC_CIVINFO_TROS_HABSBURG_POPULATION",		"en_US",	"Unknown"	),
	("LOC_CIVINFO_TROS_HABSBURG_CAPITAL",			"en_US",	"Vienna"	),
-- CIV8  - Zürich -----------------------------
	("LOC_CIVINFO_TROS_ZURICH_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_ZURICH_SIZE",			"en_US",	"1'728.95 km2"	),
	("LOC_CIVINFO_TROS_ZURICH_POPULATION",		"en_US",	"1'500'000"	),
	("LOC_CIVINFO_TROS_ZURICH_CAPITAL",			"en_US",	"Zurich"	),
	("LOC_CIVINFO_TROS_ZURICH_CAPITAL",			"de_DE",	"Zürich"	),
-- CIV9  - Bern -------------------------------
	("LOC_CIVINFO_TROS_BERN_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_BERN_SIZE",			"en_US",	"5.959,24 km²"	),
	("LOC_CIVINFO_TROS_BERN_POPULATION",		"en_US",	"1'000'000"	),
	("LOC_CIVINFO_TROS_BERN_CAPITAL",			"en_US",	"Bern"	),
-- CIV10 - Graubünden -------------------------
	("LOC_CIVINFO_TROS_GRAUBUNDEN_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_GRAUBUNDEN_SIZE",			"en_US",	"7,105 km²"	),
	("LOC_CIVINFO_TROS_GRAUBUNDEN_POPULATION",		"en_US",	"200'000"	),
	("LOC_CIVINFO_TROS_GRAUBUNDEN_CAPITAL",			"en_US",	"Chur"	),
-- CIV11 - Wallis -----------------------------
	("LOC_CIVINFO_TROS_WALLIS_LOCATION",		"en_US",	"Europe"	),
	("LOC_CIVINFO_TROS_WALLIS_SIZE",			"en_US",	"5.224 km²"	),
	("LOC_CIVINFO_TROS_WALLIS_POPULATION",		"en_US",	"340'000"	),
	("LOC_CIVINFO_TROS_WALLIS_CAPITAL",			"en_US",	"Sion"	),

-----------------------------------------------
-- Pedia
-----------------------------------------------

-- CIV1  - Eidgenossenschaft ------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_1",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_2",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_3",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_4",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_5",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_6",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_7",	"de_DE",	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_CHAPTER_HISTORY_PARA_8",	"de_DE",	"Plaecholder."),
-- CIV2  - Frankreich -------------------------
-- CIV3  - Burgund ----------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BURGUND_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV4  - Savoyen ----------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_SAVOYEN_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV5  - Deutschland ------------------------
-- CIV6  - Italien ----------------------------
-- CIV7  - Habsburg ---------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_HABSBURG_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV8  - Zürich -----------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_ZURICH_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV9  - Bern -------------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_BERN_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV10 - Graubünden -------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_GRAUBUNDEN_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder."),
-- CIV11 - Wallis -----------------------------
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_1",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_2",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_3",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_4",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_5",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_6",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_7",	"en_US",
	"Plaecholder."),
	("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_TROS_WALLIS_CHAPTER_HISTORY_PARA_8",	"en_US",
	"Plaecholder.");