---	Localisation ---

-- Types
INSERT OR REPLACE INTO LocalizedText
		(Tag,	Language,	Text)
VALUES

-- Civilization
	("LOC_CIVILIZATION_ROME_NAME",			"en_US",	"Milano"			),
	("LOC_CIVILIZATION_ROME_DESCRIPTION",	"en_US",	"Herzogtum Mailand"	),
	("LOC_CIVILIZATION_ROME_ADJECTIVE",  	"en_US",	"milanese"			),
	("LOC_CIVILIZATION_ROME_NAME",			"de_DE",	"Milano"			),
	("LOC_CIVILIZATION_ROME_DESCRIPTION",	"de_DE",	"Herzogtum Mailand"	),
	("LOC_CIVILIZATION_ROME_ADJECTIVE",  	"de_DE",	"milanese"			),

-- Cities
	("LOC_CITY_NAME_ROME_1", "en_US", "Milano"),
	("LOC_CITY_NAME_ROME_2", "en_US", "Brescia"),
	("LOC_CITY_NAME_ROME_3", "en_US", "Novara"),
	("LOC_CITY_NAME_ROME_4", "en_US", "Varese"),
	("LOC_CITY_NAME_ROME_5", "en_US", "Lecco"),
	("LOC_CITY_NAME_ROME_6", "en_US", "Busto Arsizio"),
	("LOC_CITY_NAME_ROME_7", "en_US", "Biella"),
	("LOC_CITY_NAME_ROME_8", "en_US", "Domodossola"),
	("LOC_CITY_NAME_ROME_9", "en_US", "Verona"),
	("LOC_CITY_NAME_ROME_10", "en_US", "Vicenza"),
	("LOC_CITY_NAME_ROME_11", "en_US", "Bergamo"),
	("LOC_CITY_NAME_ROME_12", "en_US", "Como"),
	("LOC_CITY_NAME_ROME_13", "en_US", "Trient"),
	("LOC_CITY_NAME_ROME_14", "en_US", "Rovereto"),
	("LOC_CITY_NAME_ROME_15", "en_US", "Bozen"),
	("LOC_CITY_NAME_ROME_16", "en_US", "Meran"),
	("LOC_CITY_NAME_ROME_1", "de_DE", "Milano"),
	("LOC_CITY_NAME_ROME_2", "de_DE", "Brescia"),
	("LOC_CITY_NAME_ROME_3", "de_DE", "Novara"),
	("LOC_CITY_NAME_ROME_4", "de_DE", "Varese"),
	("LOC_CITY_NAME_ROME_5", "de_DE", "Lecco"),
	("LOC_CITY_NAME_ROME_6", "de_DE", "Busto Arsizio"),
	("LOC_CITY_NAME_ROME_7", "de_DE", "Biella"),
	("LOC_CITY_NAME_ROME_8", "de_DE", "Domodossola"),
	("LOC_CITY_NAME_ROME_9", "de_DE", "Verona"),
	("LOC_CITY_NAME_ROME_10", "de_DE", "Vicenza"),
	("LOC_CITY_NAME_ROME_11", "de_DE", "Bergamo"),
	("LOC_CITY_NAME_ROME_12", "de_DE", "Como"),
	("LOC_CITY_NAME_ROME_13", "de_DE", "Trient"),
	("LOC_CITY_NAME_ROME_14", "de_DE", "Rovereto"),
	("LOC_CITY_NAME_ROME_15", "de_DE", "Bozen"),
	("LOC_CITY_NAME_ROME_16", "de_DE", "Meran"),
	("LOC_CITY_NAME_FRANCE_1", "en_US", "Paris"),
	("LOC_CITY_NAME_FRANCE_2", "en_US", "Lyon"),
	("LOC_CITY_NAME_FRANCE_3", "en_US", "Chaumont"),
	("LOC_CITY_NAME_FRANCE_4", "en_US", "Vesoul"),
	("LOC_CITY_NAME_FRANCE_5", "en_US", "Epinal"),
	("LOC_CITY_NAME_FRANCE_1", "de_DE", "Paris"),
	("LOC_CITY_NAME_FRANCE_2", "de_DE", "Lyon"),
	("LOC_CITY_NAME_FRANCE_3", "de_DE", "Chaumont"),
	("LOC_CITY_NAME_FRANCE_4", "de_DE", "Vesoul"),
	("LOC_CITY_NAME_FRANCE_5", "de_DE", "Epinal"),
	("LOC_CITY_NAME_AACHEN", "en_US", "Munich"),
	("LOC_CITY_NAME_COLOGNE", "en_US", "Landsberg"),
	("LOC_CITY_NAME_FRANKFURT", "en_US", "Lindau"),
	("LOC_CITY_NAME_MAGDEBURG", "en_US", "Konstanz"),
	("LOC_CITY_NAME_MAINZ", "en_US", "Colmar"),
	("LOC_CITY_NAME_HEIDELBERG", "en_US", "Biberach"),
	("LOC_CITY_NAME_TRIER", "en_US", "Schlestadt"),
	("LOC_CITY_NAME_BERLIN", "en_US", "Memmingen"),
	("LOC_CITY_NAME_ULM", "en_US", "Albstadt"),
	("LOC_CITY_NAME_HAMBURG", "en_US", "Ravensburg"),
	("LOC_CITY_NAME_DORTMUND", "en_US", "Singen"),
	("LOC_CITY_NAME_NUREMBERG", "en_US", "Tuttlingen"),
	("LOC_CITY_NAME_BREMEN", "en_US", "Donaueschingen"),
	("LOC_CITY_NAME_AUGSBURG", "en_US", "Freiburg im Breisgau"),
	("LOC_CITY_NAME_AACHEN", "de_DE", "München"),
	("LOC_CITY_NAME_COLOGNE", "de_DE", "Landsberg"),
	("LOC_CITY_NAME_FRANKFURT", "de_DE", "Lindau"),
	("LOC_CITY_NAME_MAGDEBURG", "de_DE", "Konstanz"),
	("LOC_CITY_NAME_MAINZ", "de_DE", "Colmar"),
	("LOC_CITY_NAME_HEIDELBERG", "de_DE", "Biberach"),
	("LOC_CITY_NAME_TRIER", "de_DE", "Schlestadt"),
	("LOC_CITY_NAME_BERLIN", "de_DE", "Memmingen"),
	("LOC_CITY_NAME_ULM", "de_DE", "Albstadt"),
	("LOC_CITY_NAME_HAMBURG", "de_DE", "Ravensburg"),
	("LOC_CITY_NAME_DORTMUND", "de_DE", "Singen"),
	("LOC_CITY_NAME_NUREMBERG", "de_DE", "Tuttlingen"),
	("LOC_CITY_NAME_BREMEN", "de_DE", "Donaueschingen"),
	("LOC_CITY_NAME_AUGSBURG", "de_DE", "Freiburg im Breisgau"),
	("LOC_CITY_NAME_VERONA", "en_US", "Verona"),
	("LOC_CITY_NAME_VICENZA", "en_US", "Vicenza"),
	("LOC_CITY_NAME_BERGAMO", "en_US", "Bergamo"),
	("LOC_CITY_NAME_COMO", "en_US", "Como"),
	("LOC_CITY_NAME_TRIENT", "en_US", "Trient"),
	("LOC_CITY_NAME_ROVERETO", "en_US", "Rovereto"),
	("LOC_CITY_NAME_BOZEN", "en_US", "Bozen"),
	("LOC_CITY_NAME_MERAN", "en_US", "Meran"),
	("LOC_CITY_NAME_BELLINZONA", "en_US", "Bellinzona"),
	("LOC_CITY_NAME_ZOFINGEN", "en_US", "Zofingen"),
	("LOC_CITY_NAME_THUN", "en_US", "Thun"),
	("LOC_CITY_NAME_MURTEN", "en_US", "Murten"),
	("LOC_CITY_NAME_PORRENTRUY", "en_US", "Porrentruy"),
	("LOC_CITY_NAME_BURGDORF", "en_US", "Burgdorf"),
	("LOC_CITY_NAME_RAPPERSWIL", "en_US", "Rapperswil"),
	("LOC_CITY_NAME_MALS", "en_US", "Mals"),
	("LOC_CITY_NAME_SONDRIO", "en_US", "Sondrio"),
	("LOC_CITY_NAME_ZERMATT", "en_US", "Zermatt"),
	("LOC_CITY_NAME_OYONNAX", "en_US", "Oyonnax"),
	("LOC_CITY_NAME_PONTARLIER", "en_US", "Pontarlier"),
	("LOC_CITY_NAME_NYON", "en_US", "Nyon"),
	("LOC_CITY_NAME_SINGEN", "en_US", "Singen"),
	("LOC_CITY_NAME_TUTTLINGEN", "en_US", "Tuttlingen"),
	("LOC_CITY_NAME_DONAUESCHINGEN", "en_US", "Donaueschingen"),
	("LOC_CITY_NAME_FREIBURGIMBREISGAU", "en_US", "Freiburg im Breisgau"),
	("LOC_CITY_NAME_GARMISCHPARTENKIRCHEN", "en_US", "Garmisch-Partenkirchen"),
	("LOC_CITY_NAME_DORNBIRN", "en_US", "Dornbirn"),
	("LOC_CITY_NAME_FELDKIRCH", "en_US", "Feldkirch"),
	("LOC_CITY_NAME_VERONA", "de_DE", "Verona"),
	("LOC_CITY_NAME_VICENZA", "de_DE", "Vicenza"),
	("LOC_CITY_NAME_BERGAMO", "de_DE", "Bergamo"),
	("LOC_CITY_NAME_COMO", "de_DE", "Como"),
	("LOC_CITY_NAME_TRIENT", "de_DE", "Trient"),
	("LOC_CITY_NAME_ROVERETO", "de_DE", "Rovereto"),
	("LOC_CITY_NAME_BOZEN", "de_DE", "Bozen"),
	("LOC_CITY_NAME_MERAN", "de_DE", "Meran"),
	("LOC_CITY_NAME_BELLINZONA", "de_DE", "Bellinzona"),
	("LOC_CITY_NAME_ZOFINGEN", "de_DE", "Zofingen"),
	("LOC_CITY_NAME_THUN", "de_DE", "Thun"),
	("LOC_CITY_NAME_MURTEN", "de_DE", "Murten"),
	("LOC_CITY_NAME_PORRENTRUY", "de_DE", "Porrentruy"),
	("LOC_CITY_NAME_BURGDORF", "de_DE", "Burgdorf"),
	("LOC_CITY_NAME_RAPPERSWIL", "de_DE", "Rapperswil"),
	("LOC_CITY_NAME_MALS", "de_DE", "Mals"),
	("LOC_CITY_NAME_SONDRIO", "de_DE", "Sondrio"),
	("LOC_CITY_NAME_ZERMATT", "de_DE", "Zermatt"),
	("LOC_CITY_NAME_OYONNAX", "de_DE", "Oyonnax"),
	("LOC_CITY_NAME_PONTARLIER", "de_DE", "Pontarlier"),
	("LOC_CITY_NAME_NYON", "de_DE", "Nyon"),
	("LOC_CITY_NAME_SINGEN", "de_DE", "Singen"),
	("LOC_CITY_NAME_TUTTLINGEN", "de_DE", "Tuttlingen"),
	("LOC_CITY_NAME_DONAUESCHINGEN", "de_DE", "Donaueschingen"),
	("LOC_CITY_NAME_FREIBURGIMBREISGAU", "de_DE", "Freiburg im Breisgau"),
	("LOC_CITY_NAME_GARMISCHPARTENKIRCHEN", "de_DE", "Garmisch-Partenkirchen"),
	("LOC_CITY_NAME_DORNBIRN", "de_DE", "Dornbirn"),
	("LOC_CITY_NAME_FELDKIRCH", "de_DE", "Feldkirch");
	-- wenn neue Städte hier ändern / hinzufügen: nicht vergessen die auch in TROSGeneral_Civilizatio.sql neu zu laden.


-----------------------------------------------
-- Other
-----------------------------------------------

INSERT OR REPLACE INTO LocalizedText
		(Tag,	Language,	Text)
VALUES
-- Eiger, Mönch & Jungfrau
	("LOC_FEATURE_EVEREST_NAME",	"en_US",	"Eiger, Mönch und Jungfrau"	),
	("LOC_FEATURE_EVEREST_NAME",	"de_DE",	"Eiger, Mönch und Jungfrau"	),

-- Mont Blanc
	("LOC_FEATURE_KILIMANJARO_NAME",	"en_US",	"Mont Blanc"	),
	("LOC_FEATURE_KILIMANJARO_NAME",	"de_DE",	"Mont Blanc"	),

-- Creux du Van
	("LOC_FEATURE_PIOPIOTAHI_NAME",	"en_US",	"Creux du Van"	),
	("LOC_FEATURE_PIOPIOTAHI_NAME",	"de_DE",	"Creux du Van"	),

-- Aprikosen
	("LOC_RESOURCE_CITRUS_NAME",	"en_US",	"Aprikosen"	),
	("LOC_RESOURCE_CITRUS_NAME",	"de_DE",	"Aprikosen"	);