/*
	Civilization
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_ROME',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations
-----------------------------------------------
INSERT OR REPLACE INTO	Civilizations
		(CivilizationType,		Name,							Description,							Adjective,							StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_ROME',	'LOC_CIVILIZATION_ROME_NAME',	'LOC_CIVILIZATION_ROME_DESCRIPTION',	'LOC_CIVILIZATION_ROME_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_MEDIT' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT OR REPLACE INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_1'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_2'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_3'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_4'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_5'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_6'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_7'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_8'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_9'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_10'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_11'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_12'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_13'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_14'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_15'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_16'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_1'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_2'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_3'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_4'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_5'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AACHEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_COLOGNE'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_FRANKFURT'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAGDEBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAINZ'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HEIDELBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_TRIER'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BERLIN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_ULM'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HAMBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_DORTMUND'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_NUREMBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BREMEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AUGSBURG'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_VERONA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_VICENZA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BERGAMO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_COMO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_TRIENT'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ROVERETO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BOZEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MERAN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BELLINZONA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ZOFINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_THUN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MURTEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_PORRENTRUY'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BURGDORF'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_RAPPERSWIL'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MALS'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_SONDRIO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ZERMATT'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_OYONNAX'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_PONTARLIER'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_NYON'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_SINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_TUTTLINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_DONAUESCHINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_FREIBURGIMBREISGAU'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_GARMISCHPARTENKIRCHEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_DORNBIRN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_FELDKIRCH');

		
-----------------------------------------------
-- City-States (don't forget to update city state limit in 'MapSizes')
-----------------------------------------------
