/*
	Civilization
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_ROME',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations
-----------------------------------------------
INSERT OR REPLACE INTO	Civilizations
		(CivilizationType,		Name,							Description,							Adjective,							StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_ROME',	'LOC_CIVILIZATION_ROME_NAME',	'LOC_CIVILIZATION_ROME_DESCRIPTION',	'LOC_CIVILIZATION_ROME_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_MEDIT' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT OR REPLACE INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_1'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_2'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_3'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_4'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_5'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_6'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_7'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_8'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_9'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_10'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_11'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_12'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_13'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_14'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_15'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_16'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_1'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_2'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_3'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_4'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_5'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AACHEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_COLOGNE'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_FRANKFURT'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAGDEBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAINZ'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HEIDELBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_TRIER'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BERLIN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_ULM'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HAMBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_DORTMUND'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_NUREMBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BREMEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AUGSBURG'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_VERONA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_VICENZA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BERGAMO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_COMO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_TRIENT'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ROVERETO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BOZEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MERAN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BELLINZONA'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ZOFINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_THUN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MURTEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_PORRENTRUY'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_BURGDORF'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_RAPPERSWIL'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_MALS'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_SONDRIO'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_ZERMATT'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_OYONNAX'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_PONTARLIER'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_NYON'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_SINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_TUTTLINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_DONAUESCHINGEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_FREIBURGIMBREISGAU'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_GARMISCHPARTENKIRCHEN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_DORNBIRN'),
		('CIVILIZATION_FREE_CITIES', 'LOC_CITY_NAME_FELDKIRCH');

		
-----------------------------------------------
-- City-States
-----------------------------------------------
-- CS1 Basel (AMSTERDAM)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS1_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS1_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS1_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS1_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_AMSTERDAM';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS1_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_AMSTERDAM_TRAIT';

-- CS2 Luzern (BANDAR_BRUNEI)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS2_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS2_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS2_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS2_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BANDAR_BRUNEI';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS2_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BANDAR_BRUNEI_TRAIT';

-- CS3 Glarus (BRUSSELS)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS3_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS3_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS3_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_GLARUS'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_GLARUS'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS3_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BRUSSELS';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS3_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BRUSSELS_TRAIT';

--CS4 Schaffhausen (BUENOS_AIRES)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS4_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS4_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS4_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SCHAFFHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SCHAFFHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS4_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BUENOS_AIRES';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS4_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BUENOS_AIRES_TRAIT';

--CS5 Solothurn (CARTHAGE)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS5_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS5_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS5_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SOLOTHURN'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SOLOTHURN'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS5_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_CARTHAGE';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS5_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_CARTHAGE_TRAIT';

--CS7 Sankt Gallen (HATTUSA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS7_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS7_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS7_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SANKT_GALLEN'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SANKT_GALLEN'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS7_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_HATTUSA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS7_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_HATTUSA_TRAIT';

--CS8 Lausanne (HONG_KONG)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS8_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS8_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS8_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LAUSANNE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LAUSANNE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS8_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_HONG_KONG';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS8_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_HONG_KONG_TRAIT';

--CS9 Liestal (JAKARTA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS9_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS9_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS9_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LIESTAL'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LIESTAL'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS9_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_JAKARTA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS9_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_JAKARTA_TRAIT';

--CS10 Freiburg (JERUSALEM)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS10_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS10_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS10_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_JERUSALEM';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_FREIBURG'
WHERE	CivilizationType = 'CIVILIZATION_JERUSALEM';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_FREIBURG'
WHERE	CivilizationType = 'CIVILIZATION_JERUSALEM';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS10_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_JERUSALEM';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS10_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_JERUSALEM_TRAIT';

--CS11 Neuenburg (KABUL)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS11_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS11_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS11_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_KABUL';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_NEUENBURG'
WHERE	CivilizationType = 'CIVILIZATION_KABUL';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_NEUENBURG'
WHERE	CivilizationType = 'CIVILIZATION_KABUL';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS11_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_KABUL';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS11_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_KABUL_TRAIT';

--CS12 Delémont (KANDY)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS12_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS12_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS12_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_KANDY';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_DELEMONT'
WHERE	CivilizationType = 'CIVILIZATION_KANDY';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_DELEMONT'
WHERE	CivilizationType = 'CIVILIZATION_KANDY';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS12_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_KANDY';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS12_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_KANDY_TRAIT';

--CS13 Locarno (KUMASI)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS13_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS13_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS13_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_KUMASI';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LOCARNO'
WHERE	CivilizationType = 'CIVILIZATION_KUMASI';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LOCARNO'
WHERE	CivilizationType = 'CIVILIZATION_KUMASI';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS13_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_KUMASI';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS13_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_KUMASI_TRAIT';

--CS14 Lugano (LA_VENTA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS14_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS14_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS14_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_LA_VENTA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LUGANO'
WHERE	CivilizationType = 'CIVILIZATION_LA_VENTA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LUGANO'
WHERE	CivilizationType = 'CIVILIZATION_LA_VENTA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS14_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_LA_VENTA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS14_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_LA_VENTA_TRAIT';

--CS15 Vaduz (LISBON)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS15_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS15_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS15_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_LISBON';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_VADUZ'
WHERE	CivilizationType = 'CIVILIZATION_LISBON';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_VADUZ'
WHERE	CivilizationType = 'CIVILIZATION_LISBON';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS15_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_LISBON';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS15_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_LISBON_TRAIT';

--CS16 Biel (MOHENJO_DARO)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS16_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS16_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS16_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_MOHENJO_DARO';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BIEL'
WHERE	CivilizationType = 'CIVILIZATION_MOHENJO_DARO';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BIEL'
WHERE	CivilizationType = 'CIVILIZATION_MOHENJO_DARO';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS16_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_MOHENJO_DARO';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS16_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_MOHENJO_DARO_TRAIT';

--CS17 Besançon (PRESLAV)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS17_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS17_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS17_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_PRESLAV';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BESANCON'
WHERE	CivilizationType = 'CIVILIZATION_PRESLAV';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BESANCON'
WHERE	CivilizationType = 'CIVILIZATION_PRESLAV';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS17_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_PRESLAV';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS17_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_PRESLAV_TRAIT';

--CS18 Rottweil (NAN_MADOL)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS18_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS18_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS18_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_NAN_MADOL';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_ROTTWEIL'
WHERE	CivilizationType = 'CIVILIZATION_NAN_MADOL';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_ROTTWEIL'
WHERE	CivilizationType = 'CIVILIZATION_NAN_MADOL';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS18_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_NAN_MADOL';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS18_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_NAN_MADOL_TRAIT';

--CS19 Mülhausen (SEOUL)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS19_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS19_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS19_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_SEOUL';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_MULHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_SEOUL';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_MULHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_SEOUL';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS19_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_SEOUL';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS19_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_SEOUL_TRAIT';

--CS20 Pfullendorf (STOCKHOLM)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS20_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS20_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS20_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_STOCKHOLM';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_PFULLENDORF'
WHERE	CivilizationType = 'CIVILIZATION_STOCKHOLM';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_PFULLENDORF'
WHERE	CivilizationType = 'CIVILIZATION_STOCKHOLM';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS20_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_STOCKHOLM';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS20_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_STOCKHOLM_TRAIT';

--CS21 Kempten (TORONTO)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS21_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS21_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS21_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_TORONTO';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_KEMPTEN'
WHERE	CivilizationType = 'CIVILIZATION_TORONTO';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_KEMPTEN'
WHERE	CivilizationType = 'CIVILIZATION_TORONTO';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS21_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_TORONTO';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS21_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_TORONTO_TRAIT';

--CS22 Buron (VALLETTA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS22_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS22_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS22_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_VALLETTA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BURON'
WHERE	CivilizationType = 'CIVILIZATION_VALLETTA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BURON'
WHERE	CivilizationType = 'CIVILIZATION_VALLETTA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS22_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_VALLETTA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS22_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_VALLETTA_TRAIT';

--CS23 Basel (VILNIUS)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS23_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS23_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS23_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_VILNIUS';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_VILNIUS';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_VILNIUS';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS23_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_VILNIUS';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS23_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_VILNIUS_TRAIT';

--CS24 Luzern (YEREVAN)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS24_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS24_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS24_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_YEREVAN';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_YEREVAN';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_YEREVAN';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS24_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_YEREVAN';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS24_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_YEREVAN_TRAIT';

--CS25 Mülhausen (ZANZIBAR)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS25_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS25_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS25_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_ZANZIBAR';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_MULHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_ZANZIBAR';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_MULHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_ZANZIBAR';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS25_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_ZANZIBAR';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS25_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_ZANZIBAR_TRAIT';