/*
	Civilization
*/

-----------------------------------------------
-- Types (Base\Assets\Gameplay\Civilizations.xml)
-----------------------------------------------
INSERT INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations (Base\Assets\Gameplay\Civilizations.xml)
-----------------------------------------------
INSERT INTO	Civilizations
		(CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity)
VALUES	(
		'CIVILIZATION_TROS_EIDGENOSSENSCHAFT', -- CivilizationType
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_NAME', -- Name
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_DESCRIPTION', -- Description
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_ADJECTIVE', -- Adjective
		'CIVILIZATION_LEVEL_FULL_CIV', -- StartingCivilizationLevelType
		10, -- RandomCityNameDepth
		'ETHNICITY_EURO'); -- Ethnicity

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_1'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_2'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_3'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_4'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_5'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_6'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_7');

-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------
INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,							Female	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_1',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_2',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_3',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_4',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_5',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_6',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_7',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_8',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_9',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_10',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_1',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_2',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_3',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_4',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_5',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_6',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_7',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_8',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_9',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------
INSERT INTO	CivilizationInfo
		(CivilizationType,				Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_LOCATION',		10			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_SIZE',			20			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_POPULATION',	30			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_CAPITAL',		40			);

-----------------------------------------------
-- Start Bias
-----------------------------------------------
INSERT INTO	StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'FEATURE_FOREST',	2		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'TERRAIN_GRASS',		3		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'TERRAIN_GRASS_HILLS',	3		);