/*
	Civilization
*/

-----------------------------------------------
-- Types (Base\Assets\Gameplay\Civilizations.xml)
-----------------------------------------------
INSERT INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations (Base\Assets\Gameplay\Civilizations.xml)
-----------------------------------------------
INSERT INTO	Civilizations
		(CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity)
VALUES	(
		'CIVILIZATION_TROS_EIDGENOSSENSCHAFT', -- CivilizationType
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_NAME', -- Name
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_DESCRIPTION', -- Description
		'LOC_CIVILIZATION_TROS_EIDGENOSSENSCHAFT_ADJECTIVE', -- Adjective
		'CIVILIZATION_LEVEL_FULL_CIV', -- StartingCivilizationLevelType
		10, -- RandomCityNameDepth
		'ETHNICITY_AFRICAN'); -- Ethnicity

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_1'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_2'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_3'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_4'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_5'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_6'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_7'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_8'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_9'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_10'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_11'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_12'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_13'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_14'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_15'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_16'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_17'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_18'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_19'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_20'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_21'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_22'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_23'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_24'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_25'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_26'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_27'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_28'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_29'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_30'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_31'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_32'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_33'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_34'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_35'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_36'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_37'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_38'),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT', 'LOC_CITY_NAME_TROS_EIDGENOSSENSCHAFT_39');

-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------
INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,							Female	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_1',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_2',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_3',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_4',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_5',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_6',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_7',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_8',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_9',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_MALE_10',		0 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_1',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_2',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_3',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_4',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_5',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_6',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_7',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_8',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_9',		1 		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CITIZEN_TROS_EIDGENOSSENSCHAFT_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------
INSERT INTO	CivilizationInfo
		(CivilizationType,				Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_LOCATION',		10			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_SIZE',			20			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_POPULATION',	30			),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_TROS_EIDGENOSSENSCHAFT_CAPITAL',		40			);

-----------------------------------------------
-- Start Bias
-----------------------------------------------
INSERT INTO	StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'FEATURE_FLOODPLAINS',	2		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier	)
VALUES	('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'TERRAIN_DESERT',		3		),
		('CIVILIZATION_TROS_EIDGENOSSENSCHAFT',	'TERRAIN_DESERT_HILLS',	3		);