/*
	Civilization
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_ROME',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations
-----------------------------------------------
INSERT OR REPLACE INTO	Civilizations
		(CivilizationType,				Name,									Description,								Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity				)
VALUES	('CIVILIZATION_ROME',	'LOC_CIVILIZATION_ROME_NAME',	'LOC_CIVILIZATION_ROME_DESCRIPTION',	'LOC_CIVILIZATION_ROME_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_AFRICAN' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT OR REPLACE INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_1'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_2'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_3'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_4'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_5'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_6'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_7'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_8'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_9'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_10'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_11'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_12'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_13'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_14'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_15'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_16'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_17'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_18'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_19'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_20'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_21'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_22'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_23'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_24'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_25'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_26'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_27'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_28'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_29'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_30'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_31'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_32'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_33'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_34'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_35'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_36'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_37'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_38'),
		('CIVILIZATION_ROME', 'LOC_CITY_NAME_ROME_39'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_1'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_2'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_3'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_4'),
		('CIVILIZATION_FRANCE', 'LOC_CITY_NAME_FRANCE_5'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AACHEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_COLOGNE'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_FRANKFURT'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAGDEBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_MAINZ'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HEIDELBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_TRIER'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BERLIN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_ULM'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_HAMBURG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_DORTMUND'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_NUREMBERG'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_BREMEN'),
		('CIVILIZATION_GERMANY', 'LOC_CITY_NAME_AUGSBURG');

		
-----------------------------------------------
-- City-States
-----------------------------------------------
-- CS1 Basel (AMSTERDAM)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS1_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS1_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS1_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_BASEL'
WHERE	CivilizationType = 'CIVILIZATION_AMSTERDAM';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS1_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_AMSTERDAM';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS1_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_AMSTERDAM_TRAIT';

-- CS2 Luzern (BANDAR_BRUNEI)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS2_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS2_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS2_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LUZERN'
WHERE	CivilizationType = 'CIVILIZATION_BANDAR_BRUNEI';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS2_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BANDAR_BRUNEI';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS2_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BANDAR_BRUNEI_TRAIT';

-- CS3 Glarus (BRUSSELS)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS3_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS3_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS3_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_GLARUS'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_GLARUS'
WHERE	CivilizationType = 'CIVILIZATION_BRUSSELS';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS3_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BRUSSELS';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS3_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BRUSSELS_TRAIT';

--CS4 Schaffhausen (BUENOS_AIRES)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS4_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS4_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS4_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SCHAFFHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SCHAFFHAUSEN'
WHERE	CivilizationType = 'CIVILIZATION_BUENOS_AIRES';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS4_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_BUENOS_AIRES';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS4_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_BUENOS_AIRES_TRAIT';

--CS5 Solothurn (CARTHAGE)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS5_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS5_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS5_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SOLOTHURN'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SOLOTHURN'
WHERE	CivilizationType = 'CIVILIZATION_CARTHAGE';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS5_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_CARTHAGE';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS5_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_CARTHAGE_TRAIT';

--CS7 Sankt Gallen (HATTUSA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS7_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS7_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS7_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_SANKT_GALLEN'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_SANKT_GALLEN'
WHERE	CivilizationType = 'CIVILIZATION_HATTUSA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS7_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_HATTUSA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS7_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_HATTUSA_TRAIT';

--CS8 Lausanne (HONG_KONG)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS8_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS8_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS8_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LAUSANNE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LAUSANNE'
WHERE	CivilizationType = 'CIVILIZATION_HONG_KONG';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS8_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_HONG_KONG';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS8_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_HONG_KONG_TRAIT';

--CS9 Liestal (JAKARTA)
UPDATE	Civilizations
SET		Name = 'LOC_CIVILIZATION_TROS_CS9_NAME',
		Description = 'LOC_CIVILIZATION_TROS_CS9_DESCRIPTION',
		Adjective = 'LOC_CIVILIZATION_TROS_CS9_ADJECTIVE'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	CivilizationLeaders
SET		CapitalName = 'LOC_CITY_NAME_LIESTAL'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	CityNames
SET		CityName = 'LOC_CITY_NAME_LIESTAL'
WHERE	CivilizationType = 'CIVILIZATION_JAKARTA';

UPDATE	Leaders
SET		Name = 'LOC_CIVILIZATION_TROS_CS9_NAME'
WHERE	LeaderType = 'LEADER_MINOR_CIV_JAKARTA';

UPDATE	Traits
SET		Name = 'LOC_LEADER_TROS_CS9_UA_NAME'
WHERE	TraitType = 'MINOR_CIV_JAKARTA_TRAIT';