/*
	Civilization
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_TROS_WALLIS',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations
-----------------------------------------------
INSERT INTO	Civilizations
		(CivilizationType,				Name,									Description,								Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity				)
VALUES	('CIVILIZATION_TROS_WALLIS',	'LOC_CIVILIZATION_TROS_WALLIS_NAME',	'LOC_CIVILIZATION_TROS_WALLIS_DESCRIPTION',	'LOC_CIVILIZATION_TROS_WALLIS_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_AFRICAN' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_1'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_2'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_3'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_4'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_5'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_6'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_7'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_8'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_9'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_10'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_11'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_12'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_13'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_14'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_15'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_16'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_17'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_18'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_19'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_20'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_21'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_22'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_23'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_24'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_25'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_26'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_27'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_28'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_29'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_30'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_31'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_32'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_33'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_34'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_35'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_36'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_37'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_38'),
		('CIVILIZATION_TROS_WALLIS', 'LOC_CITY_NAME_TROS_WALLIS_39');

-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------
INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,							Female	)
VALUES	('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_1',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_2',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_3',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_4',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_5',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_6',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_7',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_8',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_9',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_MALE_10',		0 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_1',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_2',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_3',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_4',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_5',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_6',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_7',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_8',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_9',		1 		),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CITIZEN_TROS_WALLIS_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------
INSERT INTO	CivilizationInfo
		(CivilizationType,				Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_TROS_WALLIS',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_TROS_WALLIS_LOCATION',		10			),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_TROS_WALLIS_SIZE',			20			),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_TROS_WALLIS_POPULATION',	30			),
		('CIVILIZATION_TROS_WALLIS',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_TROS_WALLIS_CAPITAL',		40			);

-----------------------------------------------
-- Start Bias
-----------------------------------------------
INSERT INTO	StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier	)
VALUES	('CIVILIZATION_TROS_WALLIS',	'FEATURE_FLOODPLAINS',	2		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier	)
VALUES	('CIVILIZATION_TROS_WALLIS',	'TERRAIN_DESERT',		3		),
		('CIVILIZATION_TROS_WALLIS',	'TERRAIN_DESERT_HILLS',	3		);