/*
	Civilization
*/

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_TROS_ZURICH',	'KIND_CIVILIZATION'	);

-----------------------------------------------
-- Civilizations
-----------------------------------------------
INSERT INTO	Civilizations
		(CivilizationType,				Name,									Description,								Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity				)
VALUES	('CIVILIZATION_TROS_ZURICH',	'LOC_CIVILIZATION_TROS_ZURICH_NAME',	'LOC_CIVILIZATION_TROS_ZURICH_DESCRIPTION',	'LOC_CIVILIZATION_TROS_ZURICH_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_AFRICAN' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------
INSERT INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_1'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_2'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_3'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_4'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_5'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_6'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_7'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_8'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_9'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_10'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_11'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_12'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_13'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_14'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_15'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_16'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_17'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_18'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_19'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_20'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_21'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_22'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_23'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_24'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_25'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_26'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_27'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_28'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_29'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_30'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_31'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_32'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_33'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_34'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_35'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_36'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_37'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_38'),
		('CIVILIZATION_TROS_ZURICH', 'LOC_CITY_NAME_TROS_ZURICH_39');

-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------
INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,							Female	)
VALUES	('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_1',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_2',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_3',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_4',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_5',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_6',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_7',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_8',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_9',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_MALE_10',		0 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_1',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_2',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_3',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_4',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_5',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_6',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_7',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_8',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_9',		1 		),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CITIZEN_TROS_ZURICH_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------
INSERT INTO	CivilizationInfo
		(CivilizationType,				Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_TROS_ZURICH',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_TROS_ZURICH_LOCATION',		10			),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_TROS_ZURICH_SIZE',			20			),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_TROS_ZURICH_POPULATION',	30			),
		('CIVILIZATION_TROS_ZURICH',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_TROS_ZURICH_CAPITAL',		40			);

-----------------------------------------------
-- Start Bias
-----------------------------------------------
INSERT INTO	StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier	)
VALUES	('CIVILIZATION_TROS_ZURICH',	'FEATURE_FLOODPLAINS',	2		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier	)
VALUES	('CIVILIZATION_TROS_ZURICH',	'TERRAIN_DESERT',		3		),
		('CIVILIZATION_TROS_ZURICH',	'TERRAIN_DESERT_HILLS',	3		);